# Generated by Django 2.2.12 on 2020-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201128_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odeme',
            field=models.BooleanField(default=0),
        ),
    ]
