# Generated by Django 2.2.12 on 2020-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_odeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='beden',
            field=models.CharField(default='XL', max_length=12),
            preserve_default=False,
        ),
    ]
