# Generated by Django 2.2.12 on 2020-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_beden'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odeme2',
            field=models.BooleanField(default=1),
        ),
    ]
